app/frontend/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint
from flask import render_template
from flask import send_from_directory

from app.vulnerability.views.vulncode_db import VulncodeDB
from app.auth.acls import skip_authorization

bp = Blueprint("frontend", __name__)


@bp.route("/static/<path:path>")
@skip_authorization
def serve_static(path):
    return send_from_directory("static", path)


@bp.route("/")
@skip_authorization
def serve_index():
    vcdb = VulncodeDB()
    return render_template("index.html", vcdb=vcdb)


@bp.route("/maintenance")
@skip_authorization
def maintenance():
    return render_template("maintenance.html")


@bp.route("/list_entries")
@skip_authorization
def list_entries():
    vcdb = VulncodeDB()
    return render_template("list_vuln_entries.html", vcdb=vcdb)


@bp.route("/terms")
@skip_authorization
def terms():
    return render_template("terms_text.html")

app/profile/__init__.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

app/profile/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import logging

from bouncer.constants import READ, EDIT, DELETE  # type: ignore
from flask import (
    Blueprint,
    render_template,
    g,
    abort,
    flash,
    request,
    redirect,
    url_for,
)
from sqlakeyset import get_page  # type: ignore
from sqlalchemy import desc

from app.auth.acls import requires, ensure
from app.exceptions import InvalidProducts
from app.vulnerability.views.vulncode_db import VulnViewTypesetPaginationObjectWrapper

from app import flash_error
from data.database import DEFAULT_DATABASE as db
from data.forms import VulnerabilityDetailsForm, UserProfileForm
from data.models import Vulnerability, Nvd, User
from data.models.nvd import default_nvd_view_options
from data.models.vulnerability import VulnerabilityState
from lib.utils import (
    parse_pagination_param,
    update_products,
    get_vulnerability_details,
    clean_vulnerability_changes,
)

bp = Blueprint("profile", __name__, url_prefix="/profile")
log = logging.getLogger(__name__)


def update_proposal(vuln: Vulnerability, form: VulnerabilityDetailsForm):
    form.populate_obj(vuln)

    try:
        new_products = update_products(vuln)
    except InvalidProducts as ex:
        flash_error(ex.args[0])
        return None

    with db.session.no_autoflush:
        changes = vuln.model_changes()
    # ignore metadata
    clean_vulnerability_changes(changes)
    if not changes:
        flash_error(
            "No changes detected. " "Please modify the entry first to propose a change"
        )
        return None
    log.debug("Detected changes: %r", changes)

    vuln.make_reviewable()
    db.session.add(vuln)
    db.session.commit()

    flash(
        "Your proposal is in the review queue. "
        "You can monitor progress in your Proposals Section.",
        "success",
    )
    return new_products


# Create a catch all route for profile identifiers.
@bp.route("/proposal/<vuln_id>/edit", methods=["GET", "POST"])
@requires(EDIT, Vulnerability)
def edit_proposal(vuln_id: str = None):
    vulnerability_details = get_vulnerability_details(None, vuln_id, simplify_id=False)
    view = vulnerability_details.vulnerability_view
    vuln = vulnerability_details.get_or_create_vulnerability()
    ensure(EDIT, vuln)
    form = VulnerabilityDetailsForm(obj=vuln)

    # Populate the form data from the vulnerability view if necessary.
    if form.comment.data == "":
        form.comment.data = view.comment

    if request.method == "POST" and not form.validate():
        flash_error("Your proposal contains invalid data, please correct.")

    form_submitted = form.validate_on_submit()
    if form_submitted and view.is_creator():
        new_products = update_proposal(vuln, form)
        if new_products is not None:
            view.products = [(p.vendor, p.product) for p in new_products]

    return render_template(
        "profile/edit_proposal.html",
        vulnerability_details=vulnerability_details,
        form=form,
    )


# Create a catch all route for profile identifiers.
@bp.route("/proposals")
@requires("READ_OWN", "Proposal")
def view_proposals():
    entries = db.session.query(Vulnerability, Nvd)
    entries = entries.filter(Vulnerability.creator == g.user)
    entries = entries.outerjoin(Vulnerability, Nvd.cve_id == Vulnerability.cve_id)
    entries = entries.order_by(desc(Nvd.id))

    bookmarked_page = parse_pagination_param("proposal_p")
    per_page = 10
    entries_non_processed = entries.filter(
        ~Vulnerability.state.in_(
            [VulnerabilityState.ARCHIVED, VulnerabilityState.PUBLISHED]
        )
    )
    entries_full = entries_non_processed.options(default_nvd_view_options)
    proposal_vulns = get_page(entries_full, per_page, page=bookmarked_page)
    proposal_vulns = VulnViewTypesetPaginationObjectWrapper(proposal_vulns.paging)

    entries_processed = entries.filter(
        Vulnerability.state.in_(
            [VulnerabilityState.ARCHIVED, VulnerabilityState.PUBLISHED]
        )
    )
    bookmarked_page_processed = parse_pagination_param("proposal_processed_p")
    entries_processed_full = entries_processed.options(default_nvd_view_options)
    proposal_vulns_processed = get_page(
        entries_processed_full, per_page, page=bookmarked_page_processed
    )
    proposal_vulns_processed = VulnViewTypesetPaginationObjectWrapper(
        proposal_vulns_processed.paging
    )

    return render_template(
        "profile/proposals_view.html",
        proposal_vulns=proposal_vulns,
        proposal_vulns_processed=proposal_vulns_processed,
    )


@bp.route("/<int:user_id>", methods=["GET"])
def user_profile(user_id=None):
    user: User = User.query.get_or_404(user_id)
    ensure(READ, user)

    vulns = Vulnerability.query.filter(
        Vulnerability.creator == user,
        Vulnerability.state.in_(
            [VulnerabilityState.PUBLISHED, VulnerabilityState.ARCHIVED]
        ),
    ).all()
    return render_template("profile/profile_viewer.html", user=user, vulns=vulns)


@bp.route("/", methods=["GET", "POST"])
def index():
    user = g.user
    if request.method == "GET":
        ensure(READ, user)
    else:
        ensure(EDIT, user)
    form = UserProfileForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
    vulns = Vulnerability.query.filter(
        Vulnerability.creator == user,
        Vulnerability.state.in_(
            [VulnerabilityState.PUBLISHED, VulnerabilityState.ARCHIVED]
        ),
    ).all()
    return render_template("profile/index.html", form=form, user=user, vulns=vulns)


@bp.route("/proposal/<vuln_id>/delete", methods=["GET", "POST"])
@requires(DELETE, Vulnerability)
def delete_proposal(vuln_id: str = None):
    vulnerability_details = get_vulnerability_details(None, vuln_id, simplify_id=False)
    vuln = vulnerability_details.get_vulnerability()
    if not vuln:
        abort(404)

    if vuln.state == VulnerabilityState.PUBLISHED:
        flash_error("Can't delete a published entry w/o reverting it first")
        return redirect(url_for("profile.view_proposals"))

    if vuln.state == VulnerabilityState.ARCHIVED:
        flash_error("Can't delete an archived")
        return redirect(url_for("profile.view_proposals"))

    ensure(DELETE, vuln)

    if (
        request.method != "GET"
        and request.form.get("confirm", "false").lower() == "true"
    ):
        db.session.delete(vuln)
        db.session.commit()
        flash("Entry deleted", "success")
        return redirect(url_for("profile.view_proposals"))
    return render_template(
        "vulnerability/delete.html", vuln_view=vulnerability_details.vulnerability_view
    )

templates/profile/edit_proposal.html
{% import "bootstrap/wtf.html" as wtf %}
{# TODO: Consider using "custom_bootstrap_form.html" for customizations here. #}

{% extends "base.html" %}
{% block main_content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        {% set vuln_view = vulnerability_details.vulnerability_view %}
        <h2 class="text-center">Edit proposal</h2>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        {% set edit_mode = true %}
        {% if vuln_view.needs_improvement() %}
            <div class="card my-3">
                <div class="card-body">
                    {% include 'review/feedback_card.html' %}
                    <i class="fas fa-hand-point-right fa-lg"></i> Please address the feedback and resubmit the proposal.
                </div>
            </div>
        {% endif %}
        {% include 'vulnerability/info.html' %}
    </div>
</div>
{% endblock %}

templates/profile/index.html
{% import "bootstrap/wtf.html" as wtf %}
{% from 'macros/generate_vuln_table.html' import display_vuln_column %}

{% extends "base.html" %}


{% block main_content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2 class="text-center">My Profile</h2>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        <div class="card my-3">
            <div class="card-body">
              <div class="form-group">
                <label class="control-label">Login</label>
                <span class="form-control-plaintext">{{user.login}}</span>
                <small class="form-text text-muted">Only you can see this.</small>
                <small class="form-text text-muted">Provider: {{ user.login_type | title }}</small>
              </div>
              <form method="POST" name="terms_form">
                {{ form.hidden_tag() }}
                {{ wtf.form_errors(form, hiddens="only") }}
                {% for field in form.non_hidden_fields %}
                  {{ wtf.form_field(field) }}
                {% endfor %}

                <button type="submit" class="btn btn-success">Save</button>
                <a href="{{ url_for("profile.user_profile", user_id=user.id) }}">See public version</a>
              </form>
            </div>
        </div>
    </div>
    <div class="col-sm-2 d-flex justify-content-center">
        <div class="card my-3">
            <div class="card-header">
              Public Appearance
            </div>
            <div class="card-body d-flex flex-column align-items-center">
              {% if user.avatar %}
                <img src="{{ user.avatar_resized(96) }}" alt="profile picture" class="img-thumbnail avatar_profile">
              {% endif %}
              <span>{{ user.name }}</span>
            </div>
        </div>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        <div class="card my-3">
            <div class="card-body">
                <h3 class="card-title">Contributions</h3>
                <ul>
                {%- for vuln in vulns %}
                  <li>
                    <a href="{{ url_for('vuln.vuln_view', vcdb_id=vuln.cve_id) }}">{{ vuln.cve_id }}</a>
                    ({{ display_vuln_column(vuln, 'state') }})
                  </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

templates/profile/profile_viewer.html
{% import "bootstrap/wtf.html" as wtf %}
{% from 'macros/generate_vuln_table.html' import display_vuln_column %}

{% extends "base.html" %}


{% block main_content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2 class="text-center">{{ user.name }}'s Profile</h2>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        <div class="card my-3">
            <div class="card-body">
              <!-- the 90s called, they want their tables back -->
              <div class="table-responsive">
                <table class="table table-borderless table-hover">
                  <tr>
                    <th style="width: 10%">Name:</th>
                    <td>{{ user.name }}</td>
                  </tr>
                </table>
              </div>
            </div>
        </div>
    </div>
    {% if user.avatar %}
    <div class="col-sm-2 d-flex justify-content-center">
        <div class="card my-3">
            <div class="card-body">
              <img src="{{ user.avatar_resized(96) }}" alt="profile picture" class="img-thumbnail avatar_profile">
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        <div class="card my-3">
            <div class="card-body">
                <h3 class="card-title">Contributions</h3>
                <ul>
                {%- for vuln in vulns %}
                  <li>
                    <a href="{{ url_for('vuln.vuln_view', vcdb_id=vuln.cve_id) }}">{{ vuln.cve_id }}</a>
                    ({{ display_vuln_column(vuln, 'state') }})
                  </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

templates/profile/proposals_view.html
{% extends "base.html" %}
{% block main_content %}

{% if not proposal_vulns.rows and not proposal_vulns_processed.rows %}
<div class="row my-3">
    <div class="col-md-4 offset-md-4">
        <div class="card bg-info">
            <div class="card-body">
                <h5 class="card-title text-white">Looking for a way to create a proposal?</h5>
                <div class="card-text text-white xs">
                    You can create a new proposal by doing the following:

                    <ol>
                        <li>Search for/Choose an entry you would like to change on the <a href="{{ url_for("frontend.serve_index") }}">start page</a>.
                        <li>Press the <b class="bg-dark p-1">Propose Changes</b> button</li>
                        <li>Do your changes</li>
                        <li>Press the <b class="bg-primary p-1">Propose Change</b> button</li>
                    </ol>
                    <p><b>Done!</b> Now a reviewer will take a look at your changes
                        and approve them or might give you feedback if there is
                        something to improve.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2 class="text-center">My proposals</h2>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                {% from 'macros/generate_vuln_table.html' import display_vuln_table %}
                {% from 'macros/pagination.html' import display_nvd_pagination %}
                <h5 class="card-title">
                    <p class="text-info d-inline"><b>Pending proposals</b></p>
                </h5>
                {% set vuln_columns = ['date', 'id', 'summary', 'products', 'state'] %}
                <div>
                    {{ display_vuln_table(proposal_vulns.rows, 'proposal', vuln_columns, 'vuln.vuln_review') }}
                    {{ display_nvd_pagination(proposal_vulns, 'proposal', '') }}
                </div>

                <h5 class="card-title">
                    <p class="text-info d-inline"><b>Processed proposals</b></p>
                </h5>
                {% set vuln_columns = ['date', 'id', 'summary', 'products', 'state'] %}
                <div>
                    {{ display_vuln_table(proposal_vulns_processed.rows, 'proposal_processed', vuln_columns, 'vuln.vuln_review') }}
                    {{ display_nvd_pagination(proposal_vulns_processed, 'proposal_processed', '') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}