data/models/user.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import enum
import re
import uuid
from flask.helpers import url_for

from sqlalchemy import Column, String, Integer, ForeignKey, Enum, Boolean, Table
from sqlalchemy.orm import relationship
from sqlalchemy.sql.schema import PrimaryKeyConstraint

from data.utils import populate_models
from data.models.base import MainBase, BaseModel
from lib.statemachine import StateMachine, transition


class PredefinedRoles(enum.Enum):
    USER = enum.auto()
    REVIEWER = enum.auto()
    ADMIN = enum.auto()

    def __str__(self):
        return str(self.name)


class LoginType(str, enum.Enum):
    LOCAL = "LOCAL"
    GOOGLE = "GOOGLE"
    GITHUB = "GITHUB"

    def __str__(self):
        return str(self.name)


class UserRole(BaseModel):
    role_id = Column(Integer, ForeignKey("role.id"), nullable=False, primary_key=True)
    user_id = Column(Integer, ForeignKey("user.id"), nullable=False, primary_key=True)


class Role(MainBase):
    name = Column(String(256), nullable=False, unique=True)
    users = relationship("User", secondary="user_role", back_populates="roles")

    def __str__(self):
        return str(self.name)


class InviteCode(MainBase):
    code = Column(
        String(36),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid.uuid4()),
    )
    remaining_uses = Column(Integer, nullable=False, default=1)
    description = Column(String(255), nullable=False)
    roles = relationship(Role, secondary="invite_role")
    users = relationship("User", back_populates="invite_code")


invite_roles = Table(
    "invite_role",
    BaseModel.metadata,
    Column("invite_id", ForeignKey(InviteCode.id), nullable=False),
    Column("role_id", ForeignKey(Role.id), nullable=False),
    PrimaryKeyConstraint("invite_id", "role_id"),
)


class UserState(StateMachine):
    REGISTERED = 0
    ACTIVE = 1
    BLOCKED = 2
    FIRST_LOGIN = 3

    @transition(BLOCKED, ACTIVE)
    @transition(REGISTERED, FIRST_LOGIN)
    @transition(FIRST_LOGIN, ACTIVE)
    def enable(self, current_state, next_state):  # pylint: disable=no-self-use
        del current_state, next_state
        return True

    disable = transition(ACTIVE, BLOCKED)()


class User(MainBase):
    login = Column(String(256), unique=True, nullable=False)
    full_name = Column(String(256), nullable=True)
    profile_picture = Column(String(256), nullable=True)
    roles = relationship(Role, secondary="user_role", back_populates="users")
    state = Column(Enum(UserState), default=UserState.REGISTERED, nullable=False)
    hide_name = Column(Boolean, nullable=False, default=True)
    hide_picture = Column(Boolean, nullable=False, default=True)
    invite_code_id = Column(Integer, ForeignKey(InviteCode.id), nullable=True)
    invite_code = relationship(InviteCode, back_populates="users")
    login_type = Column(Enum(LoginType), nullable=True)

    @property
    def name(self):
        if self.hide_name:
            return f"User {self.id}"
        if self.full_name:
            return self.full_name
        return self.login.split("@", 1)[0]

    @property
    def avatar(self):
        if self.hide_picture or not self.profile_picture:
            return ""
        return self.profile_picture

    def profile_picture_resized(self, px_sz):
        pic = None
        if self.profile_picture:
            pic = self._resize(self.profile_picture, px_sz)
        return pic

    def avatar_resized(self, px_sz):
        return self._resize(self.avatar, px_sz)

    @staticmethod
    def _resize(pic, px_sz):
        if "googleusercontent.com" in pic:
            pic = re.sub(r"/photo", f"/s{px_sz}-cc-rw/photo", pic)
            pic = re.sub(r"([=/])s\d+-", f"\\1s{px_sz}-", pic)
        return pic

    def to_json(self):
        """Serialize object properties as dict."""
        # TODO: Refactor how we will surface this.
        return {
            "name": self.name,
            "id": self.id,
            "profile_link": self.profile_link,
            "avatar": self.avatar,
        }

    def _has_role(self, role):
        for cur_role in self.roles:
            if cur_role.name == str(role):
                return True
        return False

    def is_admin(self):
        return self._has_role(PredefinedRoles.ADMIN)

    def is_reviewer(self):
        return self._has_role(PredefinedRoles.REVIEWER)

    def is_enabled(self):
        return self.state in (UserState.ACTIVE, UserState.FIRST_LOGIN)

    def is_first_login(self):
        return self.state == UserState.FIRST_LOGIN

    def is_blocked(self):
        return self.state == UserState.BLOCKED

    def block(self):
        self.state = self.state.next_state(UserState.BLOCKED)

    def enable(self):
        if self.state is None:
            self.state = UserState.FIRST_LOGIN
        elif self.state == UserState.REGISTERED:
            self.state = self.state.next_state(UserState.FIRST_LOGIN)
        else:
            self.state = self.state.next_state(UserState.ACTIVE)

    @property
    def profile_link(self):
        return url_for("profile.user_profile", user_id=self.id)


# must be set after all definitions
__all__ = populate_models(__name__)

app/product/__init__.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

app/product/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import Blueprint, render_template, jsonify
from sqlakeyset import get_page  # type: ignore
from sqlalchemy import and_, desc
from sqlalchemy.orm import joinedload, Load

from app.auth.acls import skip_authorization
from app.vulnerability.views.vulncode_db import (
    VulnViewTypesetPaginationObjectWrapper,
)
from data.models.nvd import default_nvd_view_options, Cpe, Nvd
from data.models.vulnerability import Vulnerability
from data.database import DEFAULT_DATABASE
from lib.utils import parse_pagination_param

bp = Blueprint("product", __name__, url_prefix="/product")
db = DEFAULT_DATABASE


def get_unique_repo_urls(vulnerability_entries):
    """
    Retrieves a unique list of repository urls sorted by frequency.
    :param vulnerability_entries:
    :return:
    """
    unique_repo_urls = {}
    for entry in vulnerability_entries:
        if entry.Vulnerability is None:
            continue
        commits = entry.Vulnerability.commits
        for commit in commits:
            repo_url = commit.repo_url
            if repo_url not in unique_repo_urls:
                unique_repo_urls[repo_url] = 0
            unique_repo_urls[repo_url] += 1

    sorted_urls = sorted(
        unique_repo_urls.items(), key=lambda item: item[1], reverse=True
    )
    repo_urls = [pair[0] for pair in sorted_urls]
    return repo_urls


def get_entries_commits(full_base_query):
    """
    Takes a base query and only selects commit relevant data.
    :param full_base_query:
    :return:
    """
    # pylint: disable=no-member
    entries_commits = full_base_query.options(Load(Vulnerability).defer("*"))
    entries_commits = entries_commits.options(Load(Nvd).defer("*"))
    # pylint: enable=no-member
    entries_commits = entries_commits.options(joinedload(Vulnerability.commits))
    entries_subset = entries_commits.all()
    return entries_subset


# Create a catch all route for product identifiers.
@bp.route("/<vendor>/<product>")
@skip_authorization
def product_view(vendor: str = None, product: str = None):
    sub_query = (
        db.session.query(Cpe.nvd_json_id)
        .filter(and_(Cpe.vendor == vendor, Cpe.product == product))
        .distinct()
    )
    number_vulns = sub_query.count()

    entries = db.session.query(Vulnerability, Nvd)
    entries = entries.filter(Nvd.id.in_(sub_query)).with_labels()
    entries = entries.outerjoin(Vulnerability, Nvd.cve_id == Vulnerability.cve_id)
    entries = entries.order_by(desc(Nvd.id))

    bookmarked_page = parse_pagination_param("product_p")

    per_page = 10
    entries_full = entries.options(default_nvd_view_options)
    product_vulns = get_page(entries_full, per_page, page=bookmarked_page)
    product_vulns = VulnViewTypesetPaginationObjectWrapper(product_vulns.paging)

    entries_commits = get_entries_commits(entries)
    repo_urls = get_unique_repo_urls(entries_commits)

    return render_template(
        "product/view.html",
        vendor=vendor,
        product=product,
        product_vulns=product_vulns,
        repo_urls=repo_urls,
        number_vulns=number_vulns,
    )


# Used for autocomplete forms supports filtering.
@bp.route("/list:<filter_term>")
@skip_authorization
def list_all(filter_term: str = None):
    if not filter_term or len(filter_term) < 3:
        return "{}"
    # Only search the product name for now.
    products = (
        db.session.query(Cpe.product, Cpe.vendor)
        .filter(Cpe.product.like(f"%{filter_term}%"))
        .distinct()
        .all()
    )
    return jsonify(products)

templates/macros/generate_vuln_table.html
{% from 'macros/products.html' import print_product_links %}
{% from 'macros/user.html' import print_user %}
{% set default_vuln_columns = ['date', 'id', 'summary', 'products', 'score', 'patch'] %}
{% set default_vuln_columns_full = default_vuln_columns + ['annotated'] %}

{% macro display_vuln_column(vuln_view, column) %}
  {% if column == "date" %}
  <span style="white-space: nowrap">
    {{ vuln_view.date_created }}
  </span>
  {% endif %}

  {% if column == "id" %}
  <span style="white-space: nowrap">
    {{ vuln_view.id or "N/A" }}
  </span>
  {% endif %}

  {% if column == "state" %}
    {% if vuln_view.state.name == 'NEW' %}
      <span class="badge badge-light">New</span>
    {% elif vuln_view.state.name == 'NEEDS_IMPROVEMENT' %}
      <span class="badge badge-danger">Needs improvement</span>
    {% elif vuln_view.state.name == 'READY' %}
      <span class="badge badge-info">Searching reviewer</span>
    {% elif vuln_view.state.name == 'IN_REVIEW' %}
      <span class="badge badge-warning">Being reviewed</span>
    {% elif vuln_view.state.name == 'REVIEWED' %}
      <span class="badge badge-success">Reviewed</span>
    {% elif vuln_view.state.name == 'PUBLISHED' %}
      <span class="badge badge-primary">Published</span>
    {% elif vuln_view.state.name == 'ARCHIVED' %}
      <span class="badge badge-dark">Archived</span>
    {% else %}
      Unknown
    {% endif %}
  {% endif %}

  {% if column == "creator" %}
    {{ print_user(vuln_view.creator) }}
  {% endif %}

  {% if column == "summary" %}
    {{ vuln_view.comment | truncate(500) if vuln_view.comment else "N/A" }}
  {% endif %}

  {% if column == "products" %}
    {% if vuln_view.products %}
      {{ print_product_links(vuln_view.products) }}
    {% else %}
      N/A
    {% endif %}
  {% endif %}

  {% if column == "score" %}
    {% if vuln_view.score %}
      {{ '%0.1f' % vuln_view.score }}
    {% else %}
      N/A
    {% endif %}
  {% endif %}

  {% if column == "patch" %}
    {% if vuln_view.master_commit is not none %}
      <i class="fa fa-check" style="color: #00FF00"></i>
    {% else %}
      <i class="fa fa-times" style="color: #FF0000"></i>
    {% endif %}
  {% endif %}

  {% if column == "annotated" %}
    {% if vuln_view.annotated %}
      <i class="fa fa-check" style="color: #00FF00"></i>
    {% else %}
      <i class="fa fa-times" style="color: #FF0000"></i>
    {% endif %}
  {% endif %}
{% endmacro %}

{% macro display_vuln_table(items, table_id, columns, url_endpoint='vuln.vuln_view') %}
  {% set columns = columns|default(default_vuln_columns, True) %}
  {% if not items or items is not iterable or items|length == 0 %}
    No results found.
  {% else %}
    <div class="table-responsive">
      <table class="table table-hover table-light" id="{{ table_id }}_tbl">
        <thead>
        <tr>
          {% for column in columns %}
            <th><b>{{ column.capitalize() }}</b></th>
          {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for vuln_view in items %}
          <tr class="clickable-row" data-href="{{
          url_for_no_querystring(url_endpoint, vcdb_id=vuln_view.id, vuln_id=vuln_view.vuln_id) }}">
            {% for column in columns %}
            <td>
              {{ display_vuln_column(vuln_view, column) }}
            </td>
            {% endfor %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endmacro %}

templates/macros/pagination.html
{% macro display_vuln_pagination(pagination, table_id, keyword) %}
  {% set base_url_params = {"keyword":keyword, "_anchor":table_id + "_tbl"} %}

  {% set page_num = table_id + '_p' %}
  <nav aria-label="Pagination">
    {{(pagination.page - 1) * pagination.per_page + 1}}-{{(pagination.page - 1) * pagination.per_page + pagination.items | length}} of <b>{{pagination.total}} entries</b>

    <ul class="pagination">
      <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
        <a class="page-link" href="{{ url_for_self(**{page_num:pagination.prev_num, "_anchor":table_id + "_tbl"}) }}" tabindex="-1">Previous</a>
      </li>

      {% set pagination_url_params = base_url_params %}
      {% for p in pagination.iter_pages(left_edge=1, left_current=2, right_current=3, right_edge=1) %}
      {% if p %}
      {% set _dummy = pagination_url_params.update({page_num:p}) %}

      {% if p != pagination.page %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for_self(**pagination_url_params) }}">{{ p }}</a>
      </li>
      {% else %}
      <li class="page-item active">
        <a class="page-link" href="{{ url_for_self(**pagination_url_params) }}">{{ p }}</a>
      </li>
      {% endif %}
      {% else %}
      <li class="page-item disabled">
        <span class="page-link ellipsis">&hellip;</span>
      </li>
      {% endif %}
      {% endfor %}

      <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
        {% set _dummy = pagination_url_params.update({page_num:pagination.next_num}) %}
        <a class="page-link" href="{{ url_for_self(**pagination_url_params) }}">Next</a>
      </li>

    </ul>
  </nav>
{% endmacro %}

{% macro display_nvd_pagination(pagination, table_id, keyword) %}
  {% set base_url_params = {"keyword":keyword, "_anchor":table_id + "_tbl"} %}
  {% set page_num = table_id + '_p' %}
  {% set pagination_url_params = base_url_params %}
  <nav aria-label="Pagination">
    <ul class="pagination">
      <li class="page-item {% if not pagination.has_previous %}disabled{% endif %}">
        {% set _dummy = pagination_url_params.update(**{page_num:pagination.bookmark_previous, "_anchor":table_id + "_tbl"}) %}
        <a class="page-link" href="{{ url_for_self(**pagination_url_params) }}" tabindex="-1">Previous</a>
      </li>

      <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
        {% set _dummy = pagination_url_params.update({page_num:pagination.bookmark_next}) %}
        <a class="page-link" href="{{ url_for_self(**pagination_url_params) }}">Next</a>
      </li>
    </ul>
  </nav>
{% endmacro %}

templates/macros/products.html
{% macro print_product_links(products) -%}
    {% for (vendor, product) in products %}
        <a class="text-info link" target="_blank" href="{{ url_for("product.product_view", vendor=vendor, product=product) }}">{{ product|title }}</a>{% if loop.index0 < products|length - 1 %},{% endif %}
    {% endfor %}
{% endmacro %}

templates/macros/statusbar.html
{% macro show_progress_statusbar(vuln_view) %}
    {% set current_state = vuln_view.state.name %}
    {% set active_step = 1 %}
    {% set next_step = '' %}

    {% if current_state == 'NEW' %}
        {% set active_step = 1 %}
        {% set next_step = 'submit for review.' %}
    {% elif current_state == 'NEEDS_IMPROVEMENT' %}
        {% set active_step = 2 %}
        {% set next_step = 'address given feedback.' %}
    {% elif current_state == 'READY' %}
        {% set active_step = 3 %}
        {% set next_step = 'wait until we find a reviewer.' %}
    {% elif current_state == 'IN_REVIEW' %}
        {% set active_step = 4 %}
        {% set next_step = 'wait for review to complete.' %}
    {% elif current_state == 'REVIEWED' %}
        {% set active_step = 5 %}
        {% set next_step = 'wait for admin approval.' %}
    {% elif current_state == 'PUBLISHED' %}
        {% set active_step = 6 %}
        {% set next_step = 'this version is live!' %}
    {% elif current_state == 'ARCHIVED' %}
        {% set active_step = 7 %}
        {% set next_step = 'this is an archived version.' %}
    {% endif %}
    <!-- Horizontal Steppers -->
    <div class="row">
        <div class="col-md-12">
            <ul class="stepper stepper-horizontal">

                <!-- Submission step -->
                <li class="{% if active_step >= 3 %}completed{% else %}active{% endif %}">
                    <a href="#!">
                        <span class="circle">{% if active_step >= 3 %}<i class="fas fa-check"></i>{% else %}<i class="fas fa-paper-plane"></i>{% endif %}</span>
                        <span class="label d-block">Submission</span>
                        {% if active_step < 3 %}<span class="label">Please {{ next_step }}</span>{% endif %}
                    </a>
                </li>
    
                <!-- Review step -->
                <li class="{% if active_step >= 5 %}completed{% elif active_step >= 3 and active_step <= 5 %}active{% endif %}">
                    <a href="#!">
                        <span class="circle">{% if active_step >= 5 %}<i class="fas fa-check"></i>{% else %}<i class="fas fa-clipboard-check"></i>{% endif %}</span>
                        <span class="label d-block">Review</span>
                        {% if active_step >= 3 and active_step < 5 %}<span class="label">Please {{ next_step }}</span>{% endif %}
                    </a>
                </li>
    
                <!-- Publication step -->
                <li class="{% if active_step >= 6 %}completed{% elif active_step == 5 %}active{% endif %}">
                    <a href="#!">
                        <span class="circle">{% if active_step >= 6 %}<i class="fas fa-check"></i>{% else %}<i class="far fa-check-circle"></i>{% endif %}</span>
                        <span class="label d-block">Publication</span>
                        {% if active_step == 5 %}
                            <span class="label">Please {{ next_step }}</span>
                        {% elif active_step > 5 %}
                            <span class="label">Complete - {{ next_step }}</span>
                        {% endif %}
                    </a>
                </li>
    
            </ul>
        </div>
    </div>
{% endmacro %}

templates/macros/text_format.html
{% macro print_link(value) -%}
  {% if value is string and value.startswith('http') %}
    <a href="{{ value }}" class="text-info" target="_blank">{{ value }}</a>
  {% elif value is iterable and value is not string and value|length > 0 %}
    {{ print_link(value[0]) }}
  {% else %}
    {{ value }}
  {% endif %}
{%- endmacro %}


{% macro print_cwes(cwes) -%}
  {% if cwes is iterable and cwes|length > 0 %}
    {% set data = [] %}
    {% for cwe in cwes %}
      <b>{{ cwe.cwe_name or "?" }}</b> (<a href="https://cwe.mitre.org/data/definitions/{{ cwe.cwe_id | replace("CWE-", "") }}.html"
      class="text-info" target="_blank">{{ cwe.cwe_id }}</a>)<br />
    {% endfor %}
  {% endif %}
{% endmacro %}

{% macro print_formatted(data, expand_label) -%}
  {% if data is iterable and data is not string and data|length > 1 %}
    {% set max_limit = 5 %}

    {% for entry in data %}
      {% if loop.index0 < max_limit %}
        &#8226; {{ print_link(entry) }} <br/>
      {% endif %}
    {% endfor %}

    {% if data|length > max_limit %}
      {% set remaining = data|length - max_limit %}
      <div>
        <a href="#" class="text-light" data-toggle="collapse" data-target="#expand_{{ expand_label }}">
          <i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
          More/Less ({{ remaining }})
        </a>
      </div>
      <div id="expand_{{ expand_label }}" class="collapse">
    {% endif %}

    {% for entry in data %}
      {% if loop.index0 >= max_limit %}
        &#8226; {{ print_link(entry) }} <br/>
      {% endif %}
    {% endfor %}

    {% if data|length > max_limit %}
      </div>
    {% endif %}

  {% else %}
    {{ print_link(data) }}
  {% endif %}
{% endmacro %}

templates/macros/user.html
{% macro print_user(user, class=None) %}
<a href="{{ user.profile_link }}" {% if class %}class="{{class}}"{% endif %}>{{ user.name }}</a>
{% endmacro %}