app/admin/routes.py
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint, render_template, request, flash
from sqlalchemy import or_

from app.auth.acls import admin_required
from data.database import DEFAULT_DATABASE
from data.models.user import InviteCode, User, UserState
from data.models.user import Role

bp = Blueprint("admin", __name__, url_prefix="/admin")
db = DEFAULT_DATABASE


def _assign(role_id, user_ids, new_state):
    del new_state
    role = Role.query.get_or_404(role_id)
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        user.roles.append(role)
        yield user


def _unassign(role_id, user_ids, new_state):
    del new_state
    role = Role.query.get_or_404(role_id)
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        user.roles.remove(role)
        yield user


def _delete(role_id, user_ids, new_state):
    del role_id, new_state
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        db.session.delete(user)
    # don't readd
    db.session.commit()
    return []


def _enable(role_id, user_ids, new_state):
    del role_id, new_state
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        user.enable()
        yield user


def _block(role_id, user_ids, new_state):
    del role_id, new_state
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        user.block()
        yield user


def _change_state(role_id, user_ids, new_state):
    del role_id
    for user_id in user_ids:
        user = User.query.get_or_404(user_id)
        user.state = UserState[new_state]
        yield user


@bp.route("/users", methods=["GET", "POST"])
@admin_required()
def users():
    if request.method == "POST":
        user_ids = request.form.getlist("user", type=int)
        action = [action for action in request.form.getlist("action") if action][0]
        role_id = request.form.get("role")
        new_state = request.form.get("state")
        changed_users = []
        functions = {
            "assign": _assign,
            "unassign": _unassign,
            "delete": _delete,
            "enable": _enable,
            "block": _block,
            "state": _change_state,
        }
        if action in functions:
            changed_users.extend(
                functions[action](
                    role_id=role_id, user_ids=user_ids, new_state=new_state
                )
            )
        else:
            flash("Invalid action", "danger")

        if changed_users:
            db.session.add_all(changed_users)
            db.session.commit()
            flash(f"Modified {len(changed_users)} user(s)", "success")

    name = request.args.get("name", default="")
    if name:
        query = f"%{name}%"
        user_list = User.query.filter(
            or_(User.login.like(query), User.full_name.like(query))
        ).paginate()
    else:
        user_list = User.query.paginate()
    roles = Role.query.all()

    return render_template(
        "admin/user_list.html",
        users=user_list,
        roles=roles,
        states=list(UserState),
        filter=name,
    )


def _create_invite_token():
    amount = request.form.get("amount", type=int)
    if not amount or amount < 1:
        flash("Invite codes have to be valid for at least one use", "danger")
        return
    roles = request.form.getlist("roles", type=int)
    if not roles or len(roles) == 0:
        flash("At least one role should be selected", "danger")
        return
    desc = request.form.get("desc")
    if not desc:
        flash("Description required", "danger")
        return

    num_roles = len(roles)
    roles = Role.query.filter(Role.id.in_(roles)).all()
    if len(roles) != num_roles:
        flash("Unknown roles provided", "danger")
        return

    db.session.add(InviteCode(roles=roles, remaining_uses=amount, description=desc))
    db.session.commit()


@bp.route("/invite_codes", methods=["GET", "POST"])
@admin_required()
def invite_codes():
    if request.method == "POST":
        if request.form.get("expire_code"):
            icode = InviteCode.query.get_or_404(
                request.form.get("expire_code", type=int)
            )
            icode.remaining_uses = 0
            db.session.add(icode)
            db.session.commit()
        else:
            _create_invite_token()
    invites = InviteCode.query.all()
    roles = Role.query.all()
    return render_template("admin/invite_codes.html", roles=roles, invite_codes=invites)

app/frontend/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint
from flask import render_template
from flask import send_from_directory

from app.vulnerability.views.vulncode_db import VulncodeDB
from app.auth.acls import skip_authorization

bp = Blueprint("frontend", __name__)


@bp.route("/static/<path:path>")
@skip_authorization
def serve_static(path):
    return send_from_directory("static", path)


@bp.route("/")
@skip_authorization
def serve_index():
    vcdb = VulncodeDB()
    return render_template("index.html", vcdb=vcdb)


@bp.route("/maintenance")
@skip_authorization
def maintenance():
    return render_template("maintenance.html")


@bp.route("/list_entries")
@skip_authorization
def list_entries():
    vcdb = VulncodeDB()
    return render_template("list_vuln_entries.html", vcdb=vcdb)


@bp.route("/terms")
@skip_authorization
def terms():
    return render_template("terms_text.html")

app/profile/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import logging

from bouncer.constants import READ, EDIT, DELETE  # type: ignore
from flask import (
    Blueprint,
    render_template,
    g,
    abort,
    flash,
    request,
    redirect,
    url_for,
)
from sqlakeyset import get_page  # type: ignore
from sqlalchemy import desc

from app.auth.acls import requires, ensure
from app.exceptions import InvalidProducts
from app.vulnerability.views.vulncode_db import VulnViewTypesetPaginationObjectWrapper

from app import flash_error
from data.database import DEFAULT_DATABASE as db
from data.forms import VulnerabilityDetailsForm, UserProfileForm
from data.models import Vulnerability, Nvd, User
from data.models.nvd import default_nvd_view_options
from data.models.vulnerability import VulnerabilityState
from lib.utils import (
    parse_pagination_param,
    update_products,
    get_vulnerability_details,
    clean_vulnerability_changes,
)

bp = Blueprint("profile", __name__, url_prefix="/profile")
log = logging.getLogger(__name__)


def update_proposal(vuln: Vulnerability, form: VulnerabilityDetailsForm):
    form.populate_obj(vuln)

    try:
        new_products = update_products(vuln)
    except InvalidProducts as ex:
        flash_error(ex.args[0])
        return None

    with db.session.no_autoflush:
        changes = vuln.model_changes()
    # ignore metadata
    clean_vulnerability_changes(changes)
    if not changes:
        flash_error(
            "No changes detected. " "Please modify the entry first to propose a change"
        )
        return None
    log.debug("Detected changes: %r", changes)

    vuln.make_reviewable()
    db.session.add(vuln)
    db.session.commit()

    flash(
        "Your proposal is in the review queue. "
        "You can monitor progress in your Proposals Section.",
        "success",
    )
    return new_products


# Create a catch all route for profile identifiers.
@bp.route("/proposal/<vuln_id>/edit", methods=["GET", "POST"])
@requires(EDIT, Vulnerability)
def edit_proposal(vuln_id: str = None):
    vulnerability_details = get_vulnerability_details(None, vuln_id, simplify_id=False)
    view = vulnerability_details.vulnerability_view
    vuln = vulnerability_details.get_or_create_vulnerability()
    ensure(EDIT, vuln)
    form = VulnerabilityDetailsForm(obj=vuln)

    # Populate the form data from the vulnerability view if necessary.
    if form.comment.data == "":
        form.comment.data = view.comment

    if request.method == "POST" and not form.validate():
        flash_error("Your proposal contains invalid data, please correct.")

    form_submitted = form.validate_on_submit()
    if form_submitted and view.is_creator():
        new_products = update_proposal(vuln, form)
        if new_products is not None:
            view.products = [(p.vendor, p.product) for p in new_products]

    return render_template(
        "profile/edit_proposal.html",
        vulnerability_details=vulnerability_details,
        form=form,
    )


# Create a catch all route for profile identifiers.
@bp.route("/proposals")
@requires("READ_OWN", "Proposal")
def view_proposals():
    entries = db.session.query(Vulnerability, Nvd)
    entries = entries.filter(Vulnerability.creator == g.user)
    entries = entries.outerjoin(Vulnerability, Nvd.cve_id == Vulnerability.cve_id)
    entries = entries.order_by(desc(Nvd.id))

    bookmarked_page = parse_pagination_param("proposal_p")
    per_page = 10
    entries_non_processed = entries.filter(
        ~Vulnerability.state.in_(
            [VulnerabilityState.ARCHIVED, VulnerabilityState.PUBLISHED]
        )
    )
    entries_full = entries_non_processed.options(default_nvd_view_options)
    proposal_vulns = get_page(entries_full, per_page, page=bookmarked_page)
    proposal_vulns = VulnViewTypesetPaginationObjectWrapper(proposal_vulns.paging)

    entries_processed = entries.filter(
        Vulnerability.state.in_(
            [VulnerabilityState.ARCHIVED, VulnerabilityState.PUBLISHED]
        )
    )
    bookmarked_page_processed = parse_pagination_param("proposal_processed_p")
    entries_processed_full = entries_processed.options(default_nvd_view_options)
    proposal_vulns_processed = get_page(
        entries_processed_full, per_page, page=bookmarked_page_processed
    )
    proposal_vulns_processed = VulnViewTypesetPaginationObjectWrapper(
        proposal_vulns_processed.paging
    )

    return render_template(
        "profile/proposals_view.html",
        proposal_vulns=proposal_vulns,
        proposal_vulns_processed=proposal_vulns_processed,
    )


@bp.route("/<int:user_id>", methods=["GET"])
def user_profile(user_id=None):
    user: User = User.query.get_or_404(user_id)
    ensure(READ, user)

    vulns = Vulnerability.query.filter(
        Vulnerability.creator == user,
        Vulnerability.state.in_(
            [VulnerabilityState.PUBLISHED, VulnerabilityState.ARCHIVED]
        ),
    ).all()
    return render_template("profile/profile_viewer.html", user=user, vulns=vulns)


@bp.route("/", methods=["GET", "POST"])
def index():
    user = g.user
    if request.method == "GET":
        ensure(READ, user)
    else:
        ensure(EDIT, user)
    form = UserProfileForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
    vulns = Vulnerability.query.filter(
        Vulnerability.creator == user,
        Vulnerability.state.in_(
            [VulnerabilityState.PUBLISHED, VulnerabilityState.ARCHIVED]
        ),
    ).all()
    return render_template("profile/index.html", form=form, user=user, vulns=vulns)


@bp.route("/proposal/<vuln_id>/delete", methods=["GET", "POST"])
@requires(DELETE, Vulnerability)
def delete_proposal(vuln_id: str = None):
    vulnerability_details = get_vulnerability_details(None, vuln_id, simplify_id=False)
    vuln = vulnerability_details.get_vulnerability()
    if not vuln:
        abort(404)

    if vuln.state == VulnerabilityState.PUBLISHED:
        flash_error("Can't delete a published entry w/o reverting it first")
        return redirect(url_for("profile.view_proposals"))

    if vuln.state == VulnerabilityState.ARCHIVED:
        flash_error("Can't delete an archived")
        return redirect(url_for("profile.view_proposals"))

    ensure(DELETE, vuln)

    if (
        request.method != "GET"
        and request.form.get("confirm", "false").lower() == "true"
    ):
        db.session.delete(vuln)
        db.session.commit()
        flash("Entry deleted", "success")
        return redirect(url_for("profile.view_proposals"))
    return render_template(
        "vulnerability/delete.html", vuln_view=vulnerability_details.vulnerability_view
    )

app/review/routes.py
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from flask import Blueprint, render_template, g
from sqlakeyset import get_page  # type: ignore
from sqlakeyset.results import s as sqlakeysetserial  # type: ignore
from sqlalchemy import desc, asc, or_
from bouncer.constants import READ  # type: ignore

from app.auth.acls import requires
from app.vulnerability.views.vulncode_db import VulnViewTypesetPaginationObjectWrapper
from data.models import Vulnerability, Nvd
from data.models.nvd import default_nvd_view_options
from data.models.vulnerability import VulnerabilityState
from data.database import DEFAULT_DATABASE
from lib.utils import parse_pagination_param

bp = Blueprint("review", __name__, url_prefix="/review")
db = DEFAULT_DATABASE


def serialize_enum(val):
    return "s", val.name


def unserialize_enum(val):
    return val


sqlakeysetserial.custom_serializations = {VulnerabilityState: serialize_enum}
sqlakeysetserial.custom_unserializations = {VulnerabilityState: unserialize_enum}


def get_pending_proposals_paged():
    entries = db.session.query(Vulnerability, Nvd)
    entries = entries.filter(Vulnerability.state != VulnerabilityState.PUBLISHED)
    entries = entries.outerjoin(Vulnerability, Nvd.cve_id == Vulnerability.cve_id)
    entries = entries.order_by(asc(Vulnerability.state), desc(Nvd.id))
    bookmarked_page = parse_pagination_param("review_p")
    per_page = 10
    entries_full = entries.options(default_nvd_view_options)
    review_vulns = get_page(entries_full, per_page, page=bookmarked_page)
    review_vulns = VulnViewTypesetPaginationObjectWrapper(review_vulns.paging)
    return review_vulns


def get_reviewed_proposals_paged():
    entries = db.session.query(Vulnerability, Nvd)
    entries = entries.filter(
        or_(
            Vulnerability.state == VulnerabilityState.PUBLISHED,
            Vulnerability.state == VulnerabilityState.REVIEWED,
            Vulnerability.state == VulnerabilityState.ARCHIVED,
        ),
        Vulnerability.reviewer == g.user,
    )
    entries = entries.outerjoin(Vulnerability, Nvd.cve_id == Vulnerability.cve_id)
    entries = entries.order_by(asc(Vulnerability.state), desc(Nvd.id))
    bookmarked_page = parse_pagination_param("reviewed_p")
    per_page = 10
    entries_full = entries.options(default_nvd_view_options)
    review_vulns = get_page(entries_full, per_page, page=bookmarked_page)
    review_vulns = VulnViewTypesetPaginationObjectWrapper(review_vulns.paging)
    return review_vulns


# Create a catch all route for profile identifiers.
@bp.route("/list")
@requires(READ, "Proposal")
def review_list():
    review_vulns = get_pending_proposals_paged()
    reviewed_vulns = get_reviewed_proposals_paged()
    return render_template(
        "review/list.html", review_vulns=review_vulns, reviewed_vulns=reviewed_vulns
    )

templates/error_generic.html
{% extends "base_nonav.html" %}
{% block main_content %}
<div class="row">
  <div class="col-sm-8 offset-md-2">
    <div class="card my-3">
      <div class="card-body">
        <h1 class="card-title">{{ error_name }}</h1>
        {% if config.DEBUG %}
        <div class="alert alert-danger" role="alert">
          {{ exception }}
        </div>
        <pre><code>{{ traceback|highlight('pytb') }}</code></pre>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">
  <!-- Footer Elements -->
  <div class="container">

    <!-- Call to action -->
    <!--
    TODO: make use of the footer.
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1">Footer</h5>
      </li>
    </ul>
    -->
    <!-- Call to action -->

  </div>
  <!-- Footer Elements -->
  <div class="footer-copyright text-center py-3">
    <p>
      <em>
        Disclaimer: Vulncode-DB is not an officially supported Google product.
      </em>
      <em>
        <b><a href="{{ url_for('auth.terms', text=True) }}">Terms of Use</a></b><br />
      </em>
      <em>
        See the <a href="https://github.com/google/vulncode-db/blob/master/README.md">vulncode-db repository</a> for more information.
      </em>
    </p>
    {% include 'footer_addon.html' ignore missing %}
  </div>
</footer>
<!-- Footer -->
{% if vulnerability_details %}
<script>
  const EDITOR_SETTINGS = {{ vulnerability_details.get_settings()|tojson }};
  window.EDITOR_SETTINGS = EDITOR_SETTINGS;
  {% if g.user %}
  const CURRENT_USER = {{ g.user.to_json()|tojson}};
  window.CURRENT_USER = CURRENT_USER;
  {% endif %}
</script>
{% endif %}

<script src="{{ url_for('frontend.serve_static', path='js/main.js') }}" type="module" crossorigin></script>
<script src="{{ url_for('frontend.serve_static', path='js/third_party/popper.min.js') }}"></script>

<script src="{{ url_for('frontend.serve_static', path='js/third_party/bootstrap.min.js') }}"></script>
<script src="{{ url_for('frontend.serve_static', path='js/third_party/mdb.min.js') }}"></script>

<!-- load monaco after all the other scripts to avoid issues with AMD defines -->
<script src="{{ url_for('frontend.serve_static', path='monaco/min/vs/loader.js') }}"></script>
<script>
 require.config(
    {paths: {'vs': "{{ url_for('frontend.serve_static', path='monaco/min/vs') }}"}});
</script>

{# TODO: This is currently disabled. Enable it again once it becomes useful.
  <script src="{{ url_for('frontend.serve_static', path='js/tutorial.js') }}" type="module"></script>
  <link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/tutorial.css') }}">
#}

templates/header.html
<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/main.css') }}"/>
<!-- See comments below for usage information. -->
<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/jstree/style.min.css') }}"/>

<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/bootstrap.min.css') }}"/>

<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/jquery.dataTables.min.css') }}"/>

<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/all.min.css') }}"/>

<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/jquery-ui.min.css') }}"/>

<!-- Polishes the CSS a bit and used for the footer. No real requirement though... TODO: drop? -->
<link rel="stylesheet" href="{{ url_for('frontend.serve_static', path='css/third_party/mdb.css') }}"/>


<!-- Used for lazyly displaying tables -->
<script src="{{ url_for('frontend.serve_static', path='js/third_party/jquery.min.js') }}"></script>

<!-- Used for lazyly displaying tables -->
<script src="{{ url_for('frontend.serve_static', path='js/third_party/jquery.dataTables.min.js') }}"></script>

<!-- Used for the editor's file navigation -->

<script src="{{ url_for('frontend.serve_static', path='js/third_party/jstree.min.js') }}"></script>

<!-- Used for the sortable plugin (comment order + drag & drop)-->
<script src="{{ url_for('frontend.serve_static', path='js/third_party/jquery-ui.min.js') }}"></script>

<!-- Used for rendering markdown comments -->
<script src="{{ url_for('frontend.serve_static', path='js/third_party/showdown.min.js') }}"></script>


<script type="text/javascript">
  const CSRF_TOKEN = "{{ csrf_token() }}";

  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", CSRF_TOKEN);
          }
      }
  });
</script>

templates/index.html
{% extends "base.html" %}
{% block main_content %}
  <div class="row">
    <div class="col-sm-8 offset-md-2">
      {% include 'index_vuln_list.html' %}
    </div>
  </div>
{% endblock %}

templates/maintenance.html
{% extends "base_nonav.html" %}
{% block main_content %}
<div class="row">
  <div class="col-lg-6 offset-md-3">
    <div class="card my-3 py-1">
      <div class="card-body" style="font-size: 1.25rem; font-family: 'Open Sans', sans-serif !important;">
        <p><strong>
            Under maintenance.<br />Please come back soon.
          </strong></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Vulncode-DB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item{%- if request.path == "/" %} active{% endif %}">
        <a class="nav-link" href="/">Home</a>
      </li>
      {% if template_exists('about.html') %}
        <li class="nav-item{%- if request.path == "/about" %} active{% endif %}">
          <a class="nav-link" href="/about">About</a>
        </li>
      {% endif %}
      {% if template_exists('end.html') %}
        <li class="nav-item{%- if request.path == "/end" %} active{% endif %}">
          <a class="nav-link" href="/end" style="color: #FF0000;font-weight: 700;">Deprecation</a>
        </li>
      {% endif %}
      {% if template_exists('news.html') %}
        <li class="nav-item{%- if request.path == "/news" %} active{% endif %}">
        <a class="nav-link" href="/news">News</a>
        </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav mt-2 mt-md-0">
      {% if g.user %}
      <li class="nav-item">
        <span class="navbar-brand">
          <a href="{{ url_for("profile.index") }}">
            {% if g.user.profile_picture %}
              <img src="{{ g.user.profile_picture_resized(30) }}" class="avatar_small d-inline-block align-top">
            {% endif %}
            {{ g.user.full_name }}
          </a>
        </span>
      </li>
        {% if is_admin() %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="adminDropdown">
              <a class="dropdown-item" href="{{ url_for("admin.users") }}">Users</a>
              <a class="dropdown-item" href="{{ url_for("admin.invite_codes") }}">Invites</a>
            </div>
          </li>
        {% endif %}
        {% if is_reviewer() %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('review.review_list') }}">
              Review

              {% set num_publishing_pending = vuln_helper.get_num_proposals_publishing_pending() %}
              {% if num_publishing_pending > 0 %}
              <span class="badge badge-success">{{ num_publishing_pending }}</span>
              {% endif %}

              {% set num_unassigned = vuln_helper.get_num_proposals_unassigned() %}
              {% set num_unassigned_to_self = vuln_helper.get_num_proposals_assigned_to(g.user) %}
              {% set num_actionable = num_unassigned + num_unassigned_to_self %}
              {% if num_actionable > 0 %}
              <span class="badge badge-danger">{{ num_actionable }}</span>
              {% endif %}

              {% set num_assigned_to_others = vuln_helper.get_num_proposals_assigned() - num_unassigned_to_self %}
              {% if num_assigned_to_others > 0 %}
              <span class="badge badge-light">{{ num_assigned_to_others }}</span>
              {% endif %}
            </a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('profile.view_proposals') }}">
            Proposals
            {% set num_proposals_action_required = vuln_helper.get_num_proposals_action_required(g.user) %}
            {% if num_proposals_action_required > 0 %}
            <span class="badge badge-danger">{{ num_proposals_action_required }}</span>
            {% endif %}

            {% set num_proposals_pending = vuln_helper.get_num_proposals_pending(g.user) %}
            {% if num_proposals_pending > 0 %}
            <span class="badge badge-light">{{ num_proposals_pending }}</span>
            {% endif %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
      {% else %}
        <a class="nav-link" href="{{ url_for('auth.login') }}">Login/Register</a>
      {% endif %}
      </li>

      <li class="nav-item">
        <span class="nav-link">&nbsp;</span>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" id="fileBugDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span style="color: #ffb500">Issues&nbsp;</span><i class="fa fa-question-circle" style="color: #ffb500"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="fileBugDropdown">
          <a class="dropdown-item" href="https://github.com/google/vulncode-db/issues/new?assignees=&labels=&template=bug_report.md&title=" target="_blank">File a bug</a>
          <a class="dropdown-item" href="https://github.com/google/vulncode-db/issues/new?assignees=&labels=&template=feature_request.md&title=" target="_blank">Feature request</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://join.slack.com/t/vulncode-db/shared_invite/zt-ja3szlcm-aevErMrmd42QVMzk89Cnkw" target="_blank">
          Slack<i class="fab fa-slack"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/vulncodedb" target="_blank">
          Twitter<i class="fab fa-twitter" style="color: #1DA1F2"></i>
        </a>
      </li>
    </ul>
    <!--
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->

  </div>
</nav>